[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
xusdc = "AZzGDkysPRAZ9cfyRo1w4rHMS51NDDNT9XqHsC1WziLM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts' --exclude 'tests/utils/**'"
